### ISSUE TITLE
[BUG] Plugin is not compatible with the latest OpenSearch 3.6.0-SNAPSHOT

### ISSUE THREAD

**Issue by mishail** [opensearch-project/cross-cluster-replication#1646]
**What is the bug?**
There were some changes introduced in https://github.com/opensearch-project/OpenSearch/pull/20585 and the plugin now has to be updated.

Two problems
1. The compilation fails with unresolved reference failures:
```
❯ ./gradlew clean precommit --refresh-dependencies
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 9.2.1
  OS Info               : Mac OS X 26.3.1 (aarch64)
  JDK Version           : 21 (Apple JDK 21 (21.0.10+7-LTS))
  JAVA_HOME             : /Library/Java/JavaVirtualMachines/applejdk-21.0.10.7.1.jdk/Contents/Home
  Random Testing Seed   : B5F3EA702CBFE2
  Crypto Standard       : any-supported
=======================================

> Task :compileKotlin FAILED
e: file:///Users/mstepura/Documents/workspace/opensearch-project/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/ReplicationEngine.kt:31:62 Unresolved reference 'IndexingStrategy'.
e: file:///Users/mstepura/Documents/workspace/opensearch-project/cross-cluster-replication/src/main/kotlin/org/opensearch/replication/ReplicationEngine.kt:35:64 Unresolved reference 'DeletionStrategy'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

This is because those two classes were moved from being inner classes in `InternalEngine` to their own files. Easy to fix just 2 imports.

2. When you done with compilation errors and tries to run the tests you see a lot of failures in ITs and you could see this in the logs

```

[2026-03-20T21:36:44,794][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [followCluster-0] fatal error in thread [opensearch[followCluster-0][write][T#3] @coroutine#13], exiting
 java.lang.AssertionError: planing as primary but got PRIMARY
 	at org.opensearch.index.engine.OperationStrategyPlanner.assertNonPrimaryOrigin(OperationStrategyPlanner.java:41)
 	at org.opensearch.index.engine.IndexingStrategyPlanner.planOperationAsNonPrimary(IndexingStrategyPlanner.java:162)
 	at org.opensearch.index.engine.InternalEngine.planIndexingAsNonPrimary(InternalEngine.java:1030)
 	at org.opensearch.replication.ReplicationEngine.indexingStrategyForOperation(ReplicationEngine.kt:34)
 	at org.opensearch.index.engine.InternalEngine.index(InternalEngine.java:929)
 	at org.opensearch.index.engine.EngineBackedIndexer.index(EngineBackedIndexer.java:53)
 	at org.opensearch.index.shard.IndexShard.index(IndexShard.java:1304)
 	at org.opensearch.index.shard.IndexShard.applyIndexOperation(IndexShard.java:1243)
 	at org.opensearch.index.shard.IndexShard.applyTranslogOperation(IndexShard.java:2720)
 	at org.opensearch.index.shard.IndexShard.applyTranslogOperation(IndexShard.java:2707)
 	at org.opensearch.replication.action.replay.TransportReplayChangesAction.performOnPrimary(TransportReplayChangesAction.kt:126)
 	at org.opensearch.replication.action.replay.TransportReplayChangesAction$dispatchedShardOperationOnPrimary$1.invokeSuspend(TransportReplayChangesAction.kt:100)
 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 	at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:918)
 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
 	at java.base/java.lang.Thread.run(Thread.java:1583)
```
